server:
  port: ${PORT:5000}

jwt:
  secret: ${JWT_SECRET_KEY}

email:
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_PASSWORD}

spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true